config/routes.rb
GolaZone::Application.routes.draw do
  get "rankings/show"

  devise_for :users

  resources :pages
  resources :campaigns do
    resources :picks
    resources :invitations, only: [:create, :destroy] do
      post "accept"
    end
    resources :competitions, only: [:create]
  end

  resources :tournaments do
    member do
      post "calculate_weeks_left"
    end
  end

  root :to => 'pages#index'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  attr_accessible :user_id, :to_email, :to_name, :campaign_id, :message

  belongs_to  :user
  belongs_to  :campaign

  validates   :to_email, uniqueness: {scope: :campaign_id}
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    @invitation = Invitation.new(params[:invitation])
    if Competition.where(user_id: User.where(email: @invitation.to_email).first, campaign_id: params[:campaign_id]).blank?
      @invitation.user_id = current_user.id
      @invitation.campaign_id = params[:campaign_id]
      @campaign = @invitation.campaign
      @user_competing = !@campaign.competitions.where(user_id: current_user).blank?
      if @invitation.save
        render partial: 'competitions/index', status: 200
        UserMailer.campaign_invitation(@invitation).deliver
      else
        render text: "#{params[:invitation][:to_email]} has already been invited", status: 406
      end
    else
      render text: "#{params[:invitation][:to_email]} is already competing in this campaign", status: 406
    end
  end

  def destroy
    @invitation = Invitation.destroy(params[:id]) if Invitation.find(params[:id]).to_email = current_user.email
    @invitations = Invitation.where(to_email: current_user.email)

    respond_to do |format|
      format.html { render partial: "invitations/pending", notice: "The invitation has been rejected" }
      format.js { render partial: "invitations/pending" }
    end
  end

  def accept
    @invitation = Invitation.find(params[:invitation_id])
    @invitation.destroy
    @invitations = Invitation.where(to_email: current_user.email)
    @competition = Competition.create(user_id: current_user.id, campaign_id: params[:campaign_id])
    @competitions = Competition.where(user_id: current_user.id)

    respond_to do |format|
      format.html { redirect_to @competition.campaign }
      format.js { render layout: false }
    end
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_new.html.haml
/ Invitation view
- if user_signed_in? && @user_competing
  = form_for @invitation, url: campaign_invitations_path(@campaign), html: {class: "invite_friend", id: "invitation"} do |f|
    .small-12.large-12.columns
      = f.text_field :to_name, placeholder: t("user.name")
      = f.email_field :to_email, placeholder: t("user.email")
      = f.text_area :message, placeholder: t("user_mailer.campaign_invitation.message"), rows: 2
      = f.submit t("user_mailer.campaign_invitation.invite"), class: "small button success radius", id: "invite_button", disable_with: t("user_mailer.campaign_invitation.inviting"), disabled: "disabled"

app/views/invitations/_pending.html.haml
/ Pending invitations
- unless @invitations.blank?
  %ul.no-bullet
    %h6= t("campaigns.pending_invitations")
    - @invitations.each do |invitation|
      %li
        = link_to invitation.campaign.name, invitation.campaign
        = link_to "<i class='general foundicon-checkmark'></i>".html_safe, campaign_invitation_accept_path(invitation.campaign, invitation.id), method: :post, remote: true,  class: "accept_invitation"
        = link_to "<i class='general foundicon-remove'></i>".html_safe, campaign_invitation_path(invitation.campaign, invitation), method: :delete, remote: true, class: "reject_invitation"

app/views/invitations/accept.js.erb
(function() {
  $("#pending_invitations").children(1).html('<%= j render "invitations/pending" %>');

  $("#competitions_list").children(1).html('<%= j render "competitions/list" %>');
})();