config/routes.rb
GolaZone::Application.routes.draw do
  get "rankings/show"

  devise_for :users

  resources :pages
  resources :campaigns do
    resources :picks
    resources :invitations, only: [:create, :destroy] do
      post "accept"
    end
    resources :competitions, only: [:create]
  end

  resources :tournaments do
    member do
      post "calculate_weeks_left"
    end
  end

  root :to => 'pages#index'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :name, :published, :number_of_matchdays, :win_points, :lose_points, :draw_points, :contest_type, :person_limit, :tournament_id, :allow_draw

  attr_accessor :allow_draw

  has_many    :competitions
  has_many    :users, through: :competitions
  belongs_to  :tournament
  has_many    :invitations

  validates :name, :number_of_matchdays, :win_points, :lose_points, :contest_type, presence: true

  # Generates the rankings for the campaign up to week_number
  #
  # week_number - the Integer number of the week
  #
  # Returns the leaderboard
  def generate_rankings(week_number)
    # If week is in the future, don't give me answer
    self.competitions.each do |comp|
      # get picks from matches that belong to the week, and the match has already been played.
      ranking = Ranking.new(competition_id: comp.id, week_id: find_week_id(week_number))
      ranking.score = Pick.count_correct(comp.picks.where(match_id: Week.find(self.find_week_id(week_number)).matches)) # ======= < This call to the DB can be made outside of the block ======
      last_total = ranking.last_week_total(comp, week_number)
      # last_total = comp.rankings.where(week_id: self.find_week_id(week_number-1)).first.total || 0
      ranking.total = last_total + ranking.score
      ranking.save
    end
  end

  # Determine if all rankings for week_number of this campaign have been generated
  # It depends on the amount of Ranking objects that already exist for this campaign on week_number
  #
  # week_number - the Integer number of the week
  #
  # Returns true if the number of Rankings in the DB for this week equal the number of competitors in this campaign
  def all_rankings_generated?(week_number)
    Ranking.where(week_id: find_week_id(week_number), competition_id: Competition.where(campaign_id: self.id).pluck(:id)).count == self.competitions.count
  end

  # Finds the id of the Week that has a week number of week_number in
  # the tournament that this campaign is referencing
  #
  # week_number - the Integer number of the week
  #
  # Returns the Integer id of the Week
  def find_week_id(week_number)
    self.tournament.weeks.where(week_number: week_number).first.id
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_filter :authenticate_user!,    :only => [:new, :create, :destroy]

  def new
    @campaign = Campaign.new
    @tournaments = Tournament.open
  end

  def index
    redirect_to new_campaign_path
  end

  def create
    @campaign = current_user.campaigns.new(params[:campaign])
    @campaign.draw_points = -1 if params[:campaign][:allow_draw] == "No"
    @campaign.competitions.build(user_id: current_user.id)
    @campaign.save
    @params = params
    redirect_to @campaign
  end

  def show
    @campaign = Campaign.find(params[:id])
    @tournament = @campaign.tournament
    @next_week = @campaign.tournament.weeks.where(week_number: @tournament.next_week).first
    @next_week = 0 if @next_week.blank?
    @current_week = @campaign.tournament.weeks.where(week_number: @tournament.current_week).first
    @user_competing = !@campaign.competitions.where(user_id: current_user).blank?
    @user_invited = !@campaign.invitations.where(to_email: current_user.email).blank? if user_signed_in?

    redirect_to root_path, alert: "You are not authorized to see this campaign" unless @campaign && (@user_competing || @user_invited || @campaign.published)

    @picks = current_user.competitions.where(campaign_id: @campaign.id).first.picks if @user_competing
    @invitation = @campaign.invitations.build(user_id: current_user.id) if user_signed_in?
    unless @campaign.all_rankings_generated?(@tournament.current_week) #&& Time.now > @current_week.latest_match
      @campaign.generate_rankings(@tournament.current_week)
    end
    @rankings = Ranking.where(competition_id: @campaign.competitions, week_id: Week.find(@current_week))#.order("score DESC")
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def tournaments_for_select
    @tournaments.map { |t| [t.name + ": " + t.season, t.id] }
  end

end

app/views/campaigns/new.html.haml
.row
  .small-12.columns.text-center
    %h2= t("campaigns.create_label")

  .small-12.medium-6.large-6.small-centered.medium-centered.large-centered.columns
    = form_for @campaign, html: { :class => "custom"} do |f|
      .row
        .small-12.columns
          - if @campaign.errors.any?
            #error_explanation.twelve.columns
              %h2= pluralize(@campaign.errors.count, "error") + t("campaigns.prohibit")
              %%ul
                - @campaign.errors.full_messages.each do |msg|
                  %li= msg

      .row.collapse
        .small-3.medium-3.large-3.columns
          %span.prefix.radius= t("campaigns.name")
        .small-9.medium-9.large-9.columns.left
          = f.text_field :name, :autofocus => true, :placeholder => t("campaigns.name_long")

      .row
        .small-3.medium-3.large-3.columns
          %label.inline= t("campaigns.audience")
        .small-6.medium-4.large-6.columns.left
          .switch.round.left
            = f.radio_button :published, true, checked: true
            %label{:for => "public", :onclick => ""}= t("campaigns.public")

            = f.radio_button :published, false
            %label{:for => "private", :onclick => ""}= t("campaigns.private")

            %span

      .row
        .small-12.medium-12.large-12.columns.left
          = f.select(:tournament_id, tournaments_for_select, { include_blank: t("campaigns.select_tournament") }, { id: "customDropdown", :class => "expand tournament_selection" })

      #matchdays.row.collapse{style: "display:none"}
        .small-4.medium-4.large-2.columns
          %span.prefix.radius= t("campaigns.play_for")
        #matchdays_for_tournament.small-4.medium-4.large-2.columns.left
          = f.number_field(:number_of_matchdays, {})
        .small-4.medium-4.large-4.columns.left
          %span.postfix.radius= t("campaigns.matchdays")

      .row
        .small-12.medium-12.large-12.columns.text-center
          %h4= t("campaigns.rules")
        .small-12.medium-12.large-12.columns.left
          = f.select(:contest_type, [[t("campaigns.round_robin"), "Round-robin"],[t("campaigns.knockout"), "Knockout"],[t("campaigns.hybrid"), "Hybrid"]], { include_blank: t("campaigns.competition") }, { id: "customDropdown2", :class => "expand contest_type_selection" })

      .row.collapse
        .small-8.medium-6.large-6.columns
          %span.prefix.radius= t("campaigns.limit")
        .small-4.medium-4.large-4.columns.left
          = f.number_field(:person_limit, {})

      .row
        .small-3.medium-3.large-3.columns
          %label.inline= t("campaigns.allow_draw")
        .small-6.medium-4.large-6.columns.left
          .switch.round.left
            = f.radio_button :allow_draw, "Yes", checked: true
            %label{:for => "yes", :onclick => ""}= t("campaigns.yea")

            = f.radio_button :allow_draw, "No"
            %label{:for => "no", :onclick => ""}= t("campaigns.nay")

            %span

      .row
        .small-12.large-8.large-centered.columns
          .row.collapse
            .small-4.medium-4.large-4.columns
              %span.prefix.radius= t("campaigns.win")
            .small-4.medium-4.large-4.columns.left
              = f.number_field(:win_points, {})
            .small-4.medium-4.large-4.columns.left
              %span.postfix.radius= t("campaigns.points")

          .row.collapse
            .small-4.medium-4.large-4.columns
              %span.prefix.radius= t("campaigns.lose")
            .small-4.medium-4.large-4.columns.left
              = f.number_field(:lose_points, {})
            .small-4.medium-4.large-4.columns.left
              %span.postfix.radius= t("campaigns.points")

          .row.collapse
            .small-4.medium-4.large-4.columns
              %span.prefix.radius= t("campaigns.draw")
            .small-4.medium-4.large-4.columns.left
              = f.number_field(:draw_points, {})
            .small-4.medium-4.large-4.columns.left
              %span.postfix.radius= t("campaigns.points")

      .row
        .small-6.large-6.columns= f.submit t("helpers.submit.submit"), class: "button expand"
        .small-6.large-6.columns= link_to t("helpers.submit.cancel"), pages_path, :class => "button secondary expand"

/ .row
/   .large-12.columns
/     %p= params
/     #debug

app/views/campaigns/show.html.haml
/ Campaign view
.row
  .small-12.text-center
    %h1= @campaign.name
    %hr

.row
  .small-12.large-3.columns
    - if @next_week == 0
      .row
        %h3.subheader.text-center= t("campaigns.winner")
        %h1.text-center#winner= @rankings.order("total DESC").first.competition.user.first_name
        %hr

    .row#competitors
      = render partial: "competitions/index"

    .row#invitations
      = render partial: "invitations/new"

  .small-12.large-3.push-6.columns
    .row
      .small-12.columns
        %h6.text-center= t("campaigns.rankings.this_week")
        = render 'rankings/leaderboard', rankings: @rankings, type: "week"
    .row
      .small-12.columns
        / %hr
        %h6.text-center= t("campaigns.rankings.standings")
        = render 'rankings/leaderboard', rankings: @rankings, type: "total"

  - unless @next_week == 0
    .small-12.large-6.pull-3.columns
      %h2.text-center= t("campaigns.next_matchday")
      = render partial: "weeks/show_week", locals: { week: @next_week, show_results: false, allow_picks: @user_competing }


  .small-12.large-6.pull-3.columns
    %h2.subheader.text-center= t("campaigns.tournament_ended") if @next_week == 0
    %h2.text-center= t("campaigns.last_matchday")
    = render "weeks/show_week", week: @current_week, show_results: true, allow_picks: false

%br.hide-for-small
%br.hide-for-small